# Generated by Django 4.1.10 on 2024-01-21 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('old_price', models.IntegerField(blank=True, null=True, verbose_name='Старая цена')),
                ('description', models.TextField(blank=True, max_length=800, verbose_name='Описание')),
                ('status', models.CharField(choices=[('PRESENT', 'Присутствует'), ('ABSENT', 'Отсутствует')], default='PRESENT', max_length=10, verbose_name='Статус')),
                ('body', models.CharField(blank=True, max_length=100, verbose_name='Корпус')),
                ('ssd', models.CharField(blank=True, max_length=100, verbose_name='SSD накопитель')),
                ('hdd', models.CharField(blank=True, max_length=100, verbose_name='Жёсткий диск')),
                ('motherboard', models.CharField(blank=True, max_length=40, verbose_name='Материнская плата')),
                ('cpu', models.CharField(blank=True, max_length=100, verbose_name='Процессор')),
                ('ram', models.CharField(blank=True, max_length=100, verbose_name='Оперативная память')),
                ('graphics_card', models.CharField(blank=True, max_length=100, verbose_name='Видеокарта')),
                ('power_supply', models.CharField(blank=True, max_length=100, verbose_name='Блок питания')),
                ('cpu_cooler', models.CharField(blank=True, max_length=100, verbose_name='Процессорный куллер')),
                ('video', models.FileField(blank=True, upload_to='builds/videos/', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Сборка',
                'verbose_name_plural': 'Сборки',
                'db_table': 'build',
            },
        ),
        migrations.CreateModel(
            name='RecommendedBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Кодовое слово')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рекомендация сборки',
                'verbose_name_plural': 'Рекомендации сборок',
            },
        ),
        migrations.CreateModel(
            name='BuildImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='Порядковый номер')),
                ('path', models.ImageField(upload_to='static/builds', verbose_name='Фото')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BuildImage', to='builds.build')),
            ],
            options={
                'verbose_name': 'Изобрежение',
                'verbose_name_plural': 'Изобажения',
                'ordering': ('order_id',),
            },
        ),
        migrations.AddField(
            model_name='build',
            name='recomendation_queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_build', to='builds.recommendedbuild', verbose_name='Рекомендательный лист'),
        ),
    ]
