# Generated by Django 3.2.12 on 2023-10-18 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('build_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('body', models.CharField(blank=True, max_length=40, verbose_name='Корпус')),
                ('ssd', models.CharField(blank=True, max_length=40, verbose_name='SSD накопитель')),
                ('motherboard', models.CharField(blank=True, max_length=40, verbose_name='Материнская плата')),
                ('cpu', models.CharField(blank=True, max_length=40, verbose_name='Процессор')),
                ('ram', models.CharField(blank=True, max_length=40, verbose_name='Оперативная память')),
                ('graphics_card', models.CharField(blank=True, max_length=40, verbose_name='Видеокарта')),
                ('power_supply', models.CharField(blank=True, max_length=40, verbose_name='Блок питания')),
                ('cpu_cooler', models.CharField(blank=True, max_length=40, verbose_name='Процессорный куллер')),
                ('title', models.CharField(max_length=40, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('old_price', models.IntegerField(blank=True, verbose_name='Старая цена')),
                ('status', models.CharField(choices=[('PRESENT', 'Присутствует'), ('ABSENT', 'Отсутствует')], max_length=10, verbose_name='Статус')),
            ],
            options={
                'db_table': 'build',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('build_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builds.build')),
            ],
        ),
    ]
