# Generated by Django 4.2.8 on 2023-12-10 16:40

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='recomendation_queue',
        ),
        migrations.AddField(
            model_name='recommendedbuild',
            name='build_list',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='recommended_builds', to='builds.build'),
        ),
    ]
