# Generated by Django 4.2.8 on 2023-12-10 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_remove_build_recomendation_queue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedbuild',
            name='build_list',
        ),
        migrations.AddField(
            model_name='build',
            name='recomendation_queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builds.recommendedbuild'),
        ),
    ]
