# Generated by Django 4.2.6 on 2023-10-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_remove_images_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='video',
            field=models.FileField(blank=True, upload_to='builds/videos/', verbose_name='Видео'),
        ),
    ]
