# Generated by Django 4.2.6 on 2023-10-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_build_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='body',
            field=models.CharField(blank=True, max_length=100, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='build',
            name='cpu',
            field=models.CharField(blank=True, max_length=100, verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='build',
            name='cpu_cooler',
            field=models.CharField(blank=True, max_length=100, verbose_name='Процессорный куллер'),
        ),
        migrations.AlterField(
            model_name='build',
            name='description',
            field=models.TextField(blank=True, max_length=800, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='build',
            name='graphics_card',
            field=models.CharField(blank=True, max_length=100, verbose_name='Видеокарта'),
        ),
        migrations.AlterField(
            model_name='build',
            name='power_supply',
            field=models.CharField(blank=True, max_length=100, verbose_name='Блок питания'),
        ),
        migrations.AlterField(
            model_name='build',
            name='ram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Оперативная память'),
        ),
        migrations.AlterField(
            model_name='build',
            name='ssd',
            field=models.CharField(blank=True, max_length=100, verbose_name='SSD накопитель'),
        ),
        migrations.AlterField(
            model_name='build',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
