# Generated by Django 4.2.8 on 2023-12-10 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_remove_recommendedbuild_build_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='recomendation_queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builds.recommendedbuild', verbose_name='Рекомендательный лист'),
        ),
    ]
