# Generated by Django 4.1.10 on 2024-01-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.CharField(max_length=9)),
                ('secondary', models.CharField(max_length=9)),
                ('text', models.CharField(max_length=9)),
                ('background', models.CharField(max_length=9)),
                ('accent', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name': 'палитра цветов',
                'verbose_name_plural': 'палитры цветов',
            },
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatId', models.TextField(max_length=100, verbose_name='ID чата')),
            ],
            options={
                'verbose_name': 'настройка чат бота',
                'verbose_name_plural': 'настройки чат бота',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(verbose_name='Режим трансляции')),
                ('link', models.TextField(verbose_name='Ссылка на трансляцию')),
            ],
            options={
                'verbose_name': 'статус трансляции',
                'verbose_name_plural': 'статусы трансляции',
            },
        ),
    ]
