# Generated by Django 3.2.12 on 2024-01-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.TextField(max_length=9)),
                ('secondary', models.TextField(max_length=9)),
                ('text', models.TextField(max_length=9)),
                ('background', models.TextField(max_length=9)),
                ('accent', models.TextField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatId', models.TextField(max_length=100, verbose_name='ID чата')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_enabled', models.BooleanField(verbose_name='Режим трансляции')),
                ('translation_link', models.TextField(verbose_name='Ссылка на трансляцию')),
            ],
        ),
    ]
