# Generated by Django 3.2.12 on 2024-01-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colors',
            options={'verbose_name': 'палитра цветов', 'verbose_name_plural': 'палитры цветов'},
        ),
        migrations.AlterModelOptions(
            name='telegram',
            options={'verbose_name': 'настройка чат бота', 'verbose_name_plural': 'настройки чат бота'},
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={'verbose_name': 'статус трансляции', 'verbose_name_plural': 'статусы трансляции'},
        ),
        migrations.AlterField(
            model_name='colors',
            name='accent',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='colors',
            name='background',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='colors',
            name='primary',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='colors',
            name='secondary',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='colors',
            name='text',
            field=models.CharField(max_length=9),
        ),
    ]
