# Generated by Django 3.2.12 on 2024-01-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_auto_20240120_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='translation_enabled',
            new_name='enabled',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='translation_link',
            new_name='link',
        ),
    ]
