# Generated by Django 4.2.7 on 2023-12-01 09:59

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='components/', verbose_name='Фото')),
                ('image_title', models.CharField(max_length=40, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Изобрaжение',
                'verbose_name_plural': 'Изобажения',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('component_type', models.CharField(choices=[('body', 'Корпус'), ('ssd', 'SSD накопитель'), ('hdd', 'Жёсткий диск'), ('motherboard', 'Материнская плата'), ('cpu', 'Процессор'), ('ram', 'Оперативная память'), ('graphics_card', 'Видеокарта'), ('cpu_cooler', 'Блок питания'), ('other', 'Другое')], max_length=20, verbose_name='Тип товара')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('old_price', models.IntegerField(blank=True, null=True, verbose_name='Старая цена')),
                ('description', models.TextField(blank=True, max_length=800, verbose_name='Описание')),
                ('status', models.CharField(choices=[('PRESENT', 'Присутствует'), ('ABSENT', 'Отсутствует')], default='PRESENT', max_length=10, verbose_name='Статус')),
                ('video', models.FileField(blank=True, upload_to='components/videos/', verbose_name='Видео')),
                ('image_list', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='components', to='components.images')),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
                'db_table': 'component',
            },
        ),
    ]
