# Generated by Django 4.2.7 on 2023-12-13 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='recomendation_queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_component', to='components.recommendedcomponent', verbose_name='Рекомендательный лист'),
        ),
    ]
