# Generated by Django 4.2.8 on 2023-12-15 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_component_recomendation_queue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='params',
        ),
        migrations.CreateModel(
            name='ComponentParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100, verbose_name='Название характеристики')),
                ('parameter_value', models.CharField(max_length=100, verbose_name='Значение')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ComponentParameter', to='components.component')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
    ]
