# Generated by Django 4.2.8 on 2023-12-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_componentparameter_component_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='params',
        ),
        migrations.DeleteModel(
            name='ComponentParameter',
        ),
        migrations.AddField(
            model_name='component',
            name='params',
            field=models.TextField(default='None', verbose_name='Параметры'),
        ),
    ]
