# Generated by Django 4.2.8 on 2023-12-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_remove_component_image_list_component_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/components/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='component',
            name='video',
            field=models.FileField(blank=True, upload_to='static/components/videos/', verbose_name='Видео'),
        ),
    ]
