# Generated by Django 4.2.8 on 2023-12-10 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_alter_component_image_alter_component_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рекомендация компонентов',
                'verbose_name_plural': 'Рекомендации компонентов',
            },
        ),
        migrations.RemoveField(
            model_name='component',
            name='image',
        ),
        migrations.CreateModel(
            name='ComponentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='Порядковый номер')),
                ('path', models.ImageField(upload_to='static/components/', verbose_name='Фото')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ComponentImage', to='components.component')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изобажения',
                'ordering': ('order_id',),
            },
        ),
        migrations.AddField(
            model_name='component',
            name='recomendation_queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.recommendedcomponent', verbose_name='Рекомендательный лист'),
        ),
    ]
